export const LIST_DETAILS_REQUEST = 'LIST_DETAILS_REQUEST';
export const LIST_DETAILS_FAILURE = 'LIST_DETAILS_FAILURE';
export const LIST_DETAILS_SUCCESS = 'LIST_DETAILS_SUCCESS';
export const DETAILS_REQUEST = 'DETAILS_REQUEST';
export const DETAILS_FAILURE = 'DETAILS_FAILURE';
export const DETAILS_SUCCESS = 'DETAILS_SUCCESS';
